### ISSUE TITLE
Updated Dockerfile and compose for development version and updated packages

### ISSUE THREAD

**Issue by iamtherobin** [getdrunkonmovies-com/TS3AudioBot_docker#18]
For anyone interested, I have updated the Dockerfile to build the image with latest dependencies (yt-dlp, ffmpeg, opus-dev) on a newer image base. I also include a simple compose file you can use to easily build the container the a compose up command.

I have tested this and it works for me on arch using latest docker and docker compose.

Dockerfile:
```
# Use latest .NET9.0 Framework Alpine release image from Microsoft.
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine-amd64

# No version arguments since this Dockerfile directly targets the development download

# TS3Audiobot images default to UID 9999. However, you may set UID to anything
# You may choose UID 1000 for convenience when mounting /app/data if you prefer
ARG PUID=9999
ENV USER=ts3bot

# Update repo to edge for latest yt-dlp
RUN sed -i 's/v3.21/edge/' /etc/apk/repositories

# Install all pre-requisites and upgrade all packages.
# The upgrade is necessary to due to the edge repo change.
RUN apk update && \
    apk add \
    opus-dev \
    yt-dlp \
    ffmpeg && \
    apk upgrade

# Download and install the TS3AudioBot development version
RUN mkdir -p /app \
    && cd /app \
    && echo "downloading https://splamy.de/api/nightly/projects/ts3ab/develop/download" \
    && wget https://splamy.de/api/nightly/projects/ts3ab/develop/download -O TS3AudioBot.zip \
    && unzip TS3AudioBot.zip \
    && rm TS3AudioBot.zip

# Add user to run under
RUN adduser --disabled-password -u "${PUID}" "${USER}"

# Make data directory and chown it to the ts3bot user
RUN mkdir -p /app/data
RUN chown -R "${USER}" /app/data

# Set user to ts3bot. No need for root past this point
USER "${USER}"

# Set the workdir so users can properly mount their config files with -v /host/path/to/data:/app/data
WORKDIR /app/data

# Expose the webserver port
EXPOSE 58913

CMD ["dotnet", "/app/TS3AudioBot.dll", "--non-interactive"]
```

Here is a basic compose file you can use to to target the Dockerfile and build from it. Make sure the Dockerfile is found inside the context directory.
```
services:
  ts3audiobot-dev:
    container_name: ts3audiobot-dev
    build:
      context: ./TS3AudioBot_docker
      dockerfile: Dockerfile-develop
    # You can set the port to access the WebUI here by changing the first number.
    ports:
      - "58913:58913"
    volumes:
      - ./ts3audiobot-data:/app/data
      #- /your/music/collection:/music:ro #You can mount your own music for local file playback
    restart: unless-stopped
    #I prefer to create my own networks for each container. But you can comment this out and use network_mode if you prefer convenience
    networks:
      - ts3audiobot
    #network_mode: "host"
      
networks:
  ts3audiobot:
    name: ts3audiobot
```
